import { useEffect, useMemo, useRef, useState } from "react";
import { flushSync } from "react-dom";

type DocumentWithViewTransitions = Document & {
  startViewTransition: (callback: () => void) => void;
};

// Crossfades the DOM between two states using the View Transitions API
// (Chrome/Edge/Safari) so the Writing <-> tag-filtered swap fades instead of
// snapping. (Search intentionally does NOT use this — it read as too fuzzy
// against the live-typing/debounce cadence.) flushSync forces the state
// update to apply synchronously so the browser captures the *new* DOM for
// the "after" snapshot — without it, startViewTransition would often
// animate nothing, since React's batched update wouldn't have painted yet.
// On browsers without support, this just runs the update directly —
// progressive enhancement, not a hard dependency.
function withViewTransition(update: () => void) {
  const doc = typeof document !== "undefined" ? (document as DocumentWithViewTransitions) : null;
  if (doc && typeof doc.startViewTransition === "function") {
    doc.startViewTransition(() => flushSync(update));
  } else {
    update();
  }
}

export type PostSummary = {
  id: string;
  title: string;
  description: string;
  status: string;
  dateLabel: string;
  readingTime: number;
  pinned: boolean;
  attribution: string;
  reviewTook: string;
  timeToPublish: string;
  tags: string[];
};

type Props = {
  posts: PostSummary[];
};

// Pagefind's runtime, generated by the `postbuild` script (`pagefind --site
// dist`) after `astro build` into dist/pagefind/pagefind.js. `astro dev` never
// runs postbuild and doesn't serve prior dist/ output, so this import 404s in
// dev — search only works via `astro build && astro preview`.
type PagefindResult = { data: () => Promise<{ url: string }> };
type PagefindModule = {
  search: (query: string) => Promise<{ results: PagefindResult[] }>;
};

function ProvenanceBadge({
  attribution,
  reviewTook,
  timeToPublish,
}: {
  attribution: string;
  reviewTook?: string;
  timeToPublish?: string;
}) {
  const timing = reviewTook
    ? `reviewed in ${reviewTook}`
    : timeToPublish
      ? `published ${timeToPublish} after drafting`
      : "";
  return (
    <span className="provenance">
      {attribution && <span className="provenance-badge">{attribution}</span>}
      {reviewTook && (
        <svg className="verified-tick" width="14" height="14" viewBox="0 0 24 24" fill="var(--accent)" role="img">
          <title>Timed review completed</title>
          <circle cx="12" cy="12" r="12" />
          <path
            d="M7 12.5l3 3 7-7"
            fill="none"
            stroke="var(--bg)"
            strokeWidth="2.2"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
      )}
      {timing && <span className="provenance-took">{timing}</span>}
    </span>
  );
}

/** Empty-search-results state — a small magnifying-glass illustration with a
 * Holmes-flavored quip, instead of a bare sentence. `compact` drops the
 * subtext for the narrow desktop dropdown; the full mobile takeover gets both. */
function NoResults({ query, compact }: { query: string; compact?: boolean }) {
  return (
    <div className={compact ? "no-results no-results-compact" : "no-results"}>
      <svg className="no-results-icon" viewBox="0 0 40 40" fill="none" aria-hidden="true">
        <circle cx="17" cy="17" r="11" stroke="currentColor" strokeWidth="2.5" />
        <line x1="25" y1="25" x2="34" y2="34" stroke="currentColor" strokeWidth="3" strokeLinecap="round" />
        <text x="17" y="21.5" textAnchor="middle" fontSize="12" fontWeight="700" fill="currentColor" fontFamily="Georgia, serif">
          ?
        </text>
      </svg>
      <p className="no-results-text">No clues found, Watson.</p>
      {!compact && <p className="no-results-subtext">Nothing matches "{query}".</p>}
    </div>
  );
}

function PostListItem({ post }: { post: PostSummary }) {
  return (
    <li>
      <a href={`/${post.id}`}>
        <span className="post-title">
          {post.status !== "published" && <span className="draft-flag">Draft</span>}
          {post.title}
        </span>
        <span className="post-meta">
          {post.dateLabel} · {post.readingTime} min read
        </span>
        <span className="post-excerpt">{post.description}</span>
        <span className="post-footer-row">
          <ProvenanceBadge attribution={post.attribution} reviewTook={post.reviewTook} timeToPublish={post.timeToPublish} />
        </span>
      </a>
    </li>
  );
}

export default function BlogPostList({ posts }: Props) {
  const pinned = useMemo(() => posts.find((p) => p.pinned), [posts]);
  // Stable reference across renders (memoized on `posts`, not recomputed
  // fresh every render) — it's a dependency of the search useEffect below,
  // and an unstable array identity there would re-fire the search on every
  // unrelated state change (e.g. clicking a tag chip).
  const writing = useMemo(() => posts.filter((p) => !p.pinned), [posts]);

  const [query, setQuery] = useState("");
  const [debouncedQuery, setDebouncedQuery] = useState("");
  const [results, setResults] = useState<PostSummary[] | null>(null);
  const [searching, setSearching] = useState(false);
  const [unavailable, setUnavailable] = useState(false);
  const pagefindRef = useRef<PagefindModule | null>(null);

  // Tag cloud — every tag across `writing` (the pinned post is excluded from
  // both the cloud and the tag filter — it's a curated highlight, not part
  // of the searchable/browsable set), most-used first, ties broken
  // alphabetically. Mutually exclusive with text search: picking a tag
  // clears the query, and typing clears the active tag (see the two
  // handlers below) — exactly one filter mode is ever active.
  const [activeTag, setActiveTag] = useState<string | null>(null);
  const tags = useMemo(() => {
    const counts = new Map<string, number>();
    for (const p of writing) {
      for (const t of p.tags) counts.set(t, (counts.get(t) ?? 0) + 1);
    }
    return [...counts.entries()].sort(
      ([aTag, aCount], [bTag, bCount]) => bCount - aCount || aTag.localeCompare(bTag),
    ).map(([t]) => t);
  }, [writing]);
  const tagged = useMemo(
    () => (activeTag ? writing.filter((p) => p.tags.includes(activeTag)) : []),
    [writing, activeTag],
  );

  function handleTagClick(tag: string) {
    withViewTransition(() => {
      setActiveTag((current) => (current === tag ? null : tag));
      // Clear both query and debouncedQuery directly (not just query) so
      // isSearching drops immediately — otherwise the 200ms debounce would
      // leave the search dropdown/results visible for a moment alongside
      // the tag-filtered view.
      setQuery("");
      setDebouncedQuery("");
    });
  }

  useEffect(() => {
    const t = window.setTimeout(() => setDebouncedQuery(query.trim()), 200);
    return () => window.clearTimeout(t);
  }, [query]);

  useEffect(() => {
    if (!debouncedQuery) {
      setResults(null);
      return;
    }
    let cancelled = false;
    setSearching(true);
    setUnavailable(false);
    (async () => {
      try {
        if (!pagefindRef.current) {
          // A string-literal specifier gets statically resolved (and fails to
          // build) even with @vite-ignore — /pagefind/pagefind.js doesn't
          // exist until pagefind's postbuild step runs on *this* build's
          // output. Building the path at runtime keeps it a genuine dynamic
          // import that Rollup can't try to bundle ahead of time.
          const pagefindUrl = ["", "pagefind", "pagefind.js"].join("/");
          pagefindRef.current = (await import(/* @vite-ignore */ pagefindUrl)) as PagefindModule;
        }
        const { results: hits } = await pagefindRef.current.search(debouncedQuery);
        const matched: PostSummary[] = [];
        for (const hit of hits) {
          const data = await hit.data();
          const slug = data.url.replace(/^\/|\/$/g, "");
          // writing (not posts) — the pinned post is excluded from search
          // results, same as it's excluded from the tag cloud/tag filter.
          const post = writing.find((p) => p.id === slug);
          if (post) matched.push(post);
        }
        if (!cancelled) setResults(matched);
      } catch {
        if (!cancelled) setUnavailable(true);
      } finally {
        if (!cancelled) setSearching(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [debouncedQuery, writing]);

  const isSearching = debouncedQuery.length > 0;

  return (
    <>
      <div className="search-panel">
        <input
          type="search"
          className="search-input"
          placeholder="Search writing…"
          value={query}
          onChange={(e) => {
            setQuery(e.target.value);
            if (activeTag) setActiveTag(null); // typing overrides a tag filter
          }}
          aria-label="Search writing"
        />

        {/* Desktop-only: a lightweight dropdown under the input — titles that
            link straight to the post (a plain navigation, full-screen read).
            Pinned/Writing stay exactly as-is underneath; nothing else on the
            page reacts to a desktop search. Hidden on mobile via CSS, which
            uses the full-takeover view in .post-column instead (below). */}
        {isSearching && (
          <div className="search-dropdown">
            {unavailable ? (
              <p className="search-dropdown-status">
                Search index not built — run <code>pnpm build</code> to test locally.
              </p>
            ) : searching && !results ? (
              <p className="search-dropdown-status">Searching…</p>
            ) : results && results.length === 0 ? (
              <NoResults query={debouncedQuery} compact />
            ) : (
              <ul className="search-dropdown-list">
                {(results ?? []).map((p) => (
                  <li key={p.id}>
                    <a href={`/${p.id}`}>{p.title}</a>
                  </li>
                ))}
              </ul>
            )}
          </div>
        )}

        {/* Fills the space below the input by default. Always rendered
            (independent of search) so it's there whether or not the dropdown
            above is open. A tag click is a discrete action, not live-typing,
            so — unlike text search — it takes over .post-column on every
            viewport, not just mobile (see data-tag-active below). */}
        {tags.length > 0 && (
          <div className="tag-cloud">
            {tags.map((t) => (
              <button
                key={t}
                type="button"
                className="tag-chip"
                aria-pressed={activeTag === t}
                onClick={() => handleTagClick(t)}
              >
                {t}
              </button>
            ))}
          </div>
        )}
      </div>

      <div
        className="post-column"
        data-searching={isSearching ? "" : undefined}
        data-tag-active={activeTag ? "" : undefined}
      >
        {/* Mobile-only full takeover: replaces Writing (and, via CSS
            sibling selector below, hides the pinned rail) so a mobile search
            shows only matches. Hidden on desktop via CSS — desktop relies on
            the dropdown above instead and never hides this default listing. */}
        <div className="mobile-search-results">
          {unavailable ? (
            <h1>Search unavailable</h1>
          ) : (
            <>
              <h1>{searching && !results ? "Searching…" : `Results for "${debouncedQuery}"`}</h1>
              {results && results.length === 0 && !searching ? (
                <NoResults query={debouncedQuery} />
              ) : (
                <ul className="post-list">
                  {(results ?? []).map((p) => (
                    <PostListItem key={p.id} post={p} />
                  ))}
                </ul>
              )}
            </>
          )}
        </div>

        <div className="default-listing">
          <h1>Writing</h1>
          {writing.length === 0 ? (
            <p className="empty">No posts yet — coming soon.</p>
          ) : (
            <ul className="post-list">
              {writing.map((p) => (
                <PostListItem key={p.id} post={p} />
              ))}
            </ul>
          )}
        </div>

        {/* A tag click takes over on every viewport (CSS below isn't
            media-gated), unlike the mobile-only search takeover above. */}
        {activeTag && (
          <div className="tag-filtered-results">
            <h1>Tagged "{activeTag}"</h1>
            <ul className="post-list">
              {tagged.map((p) => (
                <PostListItem key={p.id} post={p} />
              ))}
            </ul>
          </div>
        )}
      </div>

      {pinned && (
        <aside className="pinned-rail">
          <svg
            className="pinned-pin"
            width="200"
            height="200"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
          >
            <path d="M12 22s7-7.6 7-12A7 7 0 0 0 5 10c0 4.4 7 12 7 12z" />
            <circle cx="12" cy="10" r="2.5" />
          </svg>
          <span className="pinned-label">Pinned</span>
          <a href={`/${pinned.id}`}>
            <span className="pinned-title">{pinned.title}</span>
            <span className="pinned-excerpt">{pinned.description}</span>
            <span className="pinned-footer">
              <ProvenanceBadge
                attribution={pinned.attribution}
                reviewTook={pinned.reviewTook}
                timeToPublish={pinned.timeToPublish}
              />
            </span>
          </a>
        </aside>
      )}
    </>
  );
}
