import { useEffect, useRef, useState } from "react";

export type PostSummary = {
  id: string;
  title: string;
  description: string;
  status: string;
  dateLabel: string;
  readingTime: number;
  pinned: boolean;
  attribution: string;
  reviewTook: string;
  timeToPublish: string;
};

type Props = {
  posts: PostSummary[];
};

// Pagefind's runtime, generated by the `postbuild` script (`pagefind --site
// dist`) after `astro build` into dist/pagefind/pagefind.js. `astro dev` never
// runs postbuild and doesn't serve prior dist/ output, so this import 404s in
// dev — search only works via `astro build && astro preview`.
type PagefindResult = { data: () => Promise<{ url: string }> };
type PagefindModule = {
  search: (query: string) => Promise<{ results: PagefindResult[] }>;
};

function ProvenanceBadge({
  attribution,
  reviewTook,
  timeToPublish,
}: {
  attribution: string;
  reviewTook?: string;
  timeToPublish?: string;
}) {
  const timing = reviewTook
    ? `reviewed in ${reviewTook}`
    : timeToPublish
      ? `published ${timeToPublish} after drafting`
      : "";
  return (
    <span className="provenance">
      {attribution && <span className="provenance-badge">{attribution}</span>}
      {reviewTook && (
        <svg className="verified-tick" width="14" height="14" viewBox="0 0 24 24" fill="var(--accent)" role="img">
          <title>Timed review completed</title>
          <circle cx="12" cy="12" r="12" />
          <path
            d="M7 12.5l3 3 7-7"
            fill="none"
            stroke="var(--bg)"
            strokeWidth="2.2"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
      )}
      {timing && <span className="provenance-took">{timing}</span>}
    </span>
  );
}

/** Empty-search-results state — a small magnifying-glass illustration with a
 * Holmes-flavored quip, instead of a bare sentence. `compact` drops the
 * subtext for the narrow desktop dropdown; the full mobile takeover gets both. */
function NoResults({ query, compact }: { query: string; compact?: boolean }) {
  return (
    <div className={compact ? "no-results no-results-compact" : "no-results"}>
      <svg className="no-results-icon" viewBox="0 0 40 40" fill="none" aria-hidden="true">
        <circle cx="17" cy="17" r="11" stroke="currentColor" strokeWidth="2.5" />
        <line x1="25" y1="25" x2="34" y2="34" stroke="currentColor" strokeWidth="3" strokeLinecap="round" />
        <text x="17" y="21.5" textAnchor="middle" fontSize="12" fontWeight="700" fill="currentColor" fontFamily="Georgia, serif">
          ?
        </text>
      </svg>
      <p className="no-results-text">No clues found, Watson.</p>
      {!compact && <p className="no-results-subtext">Nothing matches "{query}".</p>}
    </div>
  );
}

function PostListItem({ post }: { post: PostSummary }) {
  return (
    <li>
      <a href={`/${post.id}`}>
        <span className="post-title">
          {post.status !== "published" && <span className="draft-flag">Draft</span>}
          {post.title}
        </span>
        <span className="post-meta">
          {post.dateLabel} · {post.readingTime} min read
        </span>
        <span className="post-excerpt">{post.description}</span>
        <span className="post-footer-row">
          <ProvenanceBadge attribution={post.attribution} reviewTook={post.reviewTook} timeToPublish={post.timeToPublish} />
        </span>
      </a>
    </li>
  );
}

export default function BlogPostList({ posts }: Props) {
  const pinned = posts.find((p) => p.pinned);
  const writing = posts.filter((p) => !p.pinned);

  const [query, setQuery] = useState("");
  const [debouncedQuery, setDebouncedQuery] = useState("");
  const [results, setResults] = useState<PostSummary[] | null>(null);
  const [searching, setSearching] = useState(false);
  const [unavailable, setUnavailable] = useState(false);
  const pagefindRef = useRef<PagefindModule | null>(null);

  useEffect(() => {
    const t = window.setTimeout(() => setDebouncedQuery(query.trim()), 200);
    return () => window.clearTimeout(t);
  }, [query]);

  useEffect(() => {
    if (!debouncedQuery) {
      setResults(null);
      return;
    }
    let cancelled = false;
    setSearching(true);
    setUnavailable(false);
    (async () => {
      try {
        if (!pagefindRef.current) {
          // A string-literal specifier gets statically resolved (and fails to
          // build) even with @vite-ignore — /pagefind/pagefind.js doesn't
          // exist until pagefind's postbuild step runs on *this* build's
          // output. Building the path at runtime keeps it a genuine dynamic
          // import that Rollup can't try to bundle ahead of time.
          const pagefindUrl = ["", "pagefind", "pagefind.js"].join("/");
          pagefindRef.current = (await import(/* @vite-ignore */ pagefindUrl)) as PagefindModule;
        }
        const { results: hits } = await pagefindRef.current.search(debouncedQuery);
        const matched: PostSummary[] = [];
        for (const hit of hits) {
          const data = await hit.data();
          const slug = data.url.replace(/^\/|\/$/g, "");
          const post = posts.find((p) => p.id === slug);
          if (post) matched.push(post);
        }
        if (!cancelled) setResults(matched);
      } catch {
        if (!cancelled) setUnavailable(true);
      } finally {
        if (!cancelled) setSearching(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [debouncedQuery, posts]);

  const isSearching = debouncedQuery.length > 0;

  return (
    <>
      <div className="search-panel">
        <input
          type="search"
          className="search-input"
          placeholder="Search writing…"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          aria-label="Search writing"
        />

        {/* Desktop-only: a lightweight dropdown under the input — titles that
            link straight to the post (a plain navigation, full-screen read).
            Pinned/Writing stay exactly as-is underneath; nothing else on the
            page reacts to a desktop search. Hidden on mobile via CSS, which
            uses the full-takeover view in .post-column instead (below). */}
        {isSearching && (
          <div className="search-dropdown">
            {unavailable ? (
              <p className="search-dropdown-status">
                Search index not built — run <code>pnpm build</code> to test locally.
              </p>
            ) : searching && !results ? (
              <p className="search-dropdown-status">Searching…</p>
            ) : results && results.length === 0 ? (
              <NoResults query={debouncedQuery} compact />
            ) : (
              <ul className="search-dropdown-list">
                {(results ?? []).map((p) => (
                  <li key={p.id}>
                    <a href={`/${p.id}`}>{p.title}</a>
                  </li>
                ))}
              </ul>
            )}
          </div>
        )}
      </div>

      <div className="post-column" data-searching={isSearching ? "" : undefined}>
        {/* Mobile-only full takeover: replaces Writing (and, via CSS
            sibling selector below, hides the pinned rail) so a mobile search
            shows only matches. Hidden on desktop via CSS — desktop relies on
            the dropdown above instead and never hides this default listing. */}
        <div className="mobile-search-results">
          {unavailable ? (
            <h1>Search unavailable</h1>
          ) : (
            <>
              <h1>{searching && !results ? "Searching…" : `Results for "${debouncedQuery}"`}</h1>
              {results && results.length === 0 && !searching ? (
                <NoResults query={debouncedQuery} />
              ) : (
                <ul className="post-list">
                  {(results ?? []).map((p) => (
                    <PostListItem key={p.id} post={p} />
                  ))}
                </ul>
              )}
            </>
          )}
        </div>

        <div className="default-listing">
          <h1>Writing</h1>
          {writing.length === 0 ? (
            <p className="empty">No posts yet — coming soon.</p>
          ) : (
            <ul className="post-list">
              {writing.map((p) => (
                <PostListItem key={p.id} post={p} />
              ))}
            </ul>
          )}
        </div>
      </div>

      {pinned && (
        <aside className="pinned-rail">
          <svg
            className="pinned-pin"
            width="200"
            height="200"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
          >
            <path d="M12 22s7-7.6 7-12A7 7 0 0 0 5 10c0 4.4 7 12 7 12z" />
            <circle cx="12" cy="10" r="2.5" />
          </svg>
          <span className="pinned-label">Pinned</span>
          <a href={`/${pinned.id}`}>
            <span className="pinned-title">{pinned.title}</span>
            <span className="pinned-excerpt">{pinned.description}</span>
            <span className="pinned-footer">
              <ProvenanceBadge
                attribution={pinned.attribution}
                reviewTook={pinned.reviewTook}
                timeToPublish={pinned.timeToPublish}
              />
            </span>
          </a>
        </aside>
      )}
    </>
  );
}
